name: edgehead
version: 0.0.1
description: A demo of fractal_stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  sass: '^0.4.2'
  built_collection: ^1.2.0
  built_value: ">=0.5.3 <1.0.0"
  egamebook:
    path: ../egamebook
  meta: any
  logging: any
  path: any
  slot_machine:
    path: ../slot_machine

dev_dependencies:
  build_runner: any
  built_value_generator: any
  simple_preprocessor: any
  source_gen: ">=0.5.4+2 <1.0.0"
  test: ">=0.12.19+1 <1.0.0"

transformers:
- simple_preprocessor
- dart_to_js_script_rewriter
- sass