name: edgehead
version: 1.0.0
description: A game of fractal_stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  browser: ^0.10.0+2
  built_collection: ^1.4.1
  built_value: ^4.1.1
  egamebook:
    path: ../egamebook
  gtag_analytics: ^0.1.3
  meta: ^1.0.5
  logging: ^0.11.3+1
  path: ^1.4.2
  quiver: ^0.25.0
  sass: ^0.4.2+7
  slot_machine:
    path: ../slot_machine

dev_dependencies:
  build_runner: ^0.5.0
  built_value_generator: ^4.1.1
  code_builder: ^1.0.4
  recase: ^1.0.0+1
  source_gen: ^0.7.1
  test: ">=0.12.19+1 <1.0.0"

transformers:
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
- sass
