name: edgehead
version: 0.0.1
description: A demo of fractal_stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^0.1.0+4
  built_collection: ^1.4.1
  built_value: ^1.2.1
  egamebook:
    path: ../egamebook
  meta: ^1.0.5
  logging: ^0.11.3+1
  path: ^1.4.2
  quiver: ^0.25.0
  sass: ^0.4.2+7
  slot_machine:
    path: ../slot_machine

dev_dependencies:
  build_runner: ^0.3.0+1
  built_value_generator: ^1.0.1
  code_builder: ^1.0.4
  recase: ^1.0.0+1
  source_gen: ">=0.5.4+2 <1.0.0"
  test: ">=0.12.19+1 <1.0.0"

transformers:
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
- dart_to_js_script_rewriter
- sass
